### ISSUE TITLE
[request] Kebutuhan Mapping enum

### ISSUE THREAD

**Issue by rizal76** [mufid/kanade#1]
Request untuk handle kasus mapping enum yang beda,
Misalnya: enum di server "SUCCESS" belum tentu di client / mapping yang diharapkan "SUCCESS" juga, terkadang ada yang di mapping lagi jadi "BERHASIL" .

Thanks  kk

**Comment by mufid** [comment]
Proposal:
- Enum akan dikonversi sebagai sebuah "symbol"
- Enum adalah sebuah option
- Enum memiliki kontrak sendiri, yang bisa dipilih dari naming strategy
- Akan ada sebuah hash yang nge-map antara nilai stringnya menjadi symbol yang seharusnya.

Contoh:

```
STATUS_MAP = {
  success: 'SYS_SUCCESS',
  abort: 'SYS_ABORTED',
}

field :status, as: :symbol, map: STATUS_MAP
```
